// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/books" | "/books/[id]" | "/dashboard/admin" | "/dashboard/admin/bookApproval" | "/dashboard/admin/manageBooks" | "/dashboard/admin/overview" | "/dashboard/admin/profile" | "/dashboard/admin/users" | "/dashboard/admin/viewTransactions" | "/dashboard/librarian" | "/dashboard/librarian/addBook" | "/dashboard/librarian/manageDeliveries" | "/dashboard/librarian/manageInventory" | "/dashboard/librarian/overview" | "/dashboard/librarian/profile" | "/dashboard/user" | "/dashboard/user/myReadingList" | "/dashboard/user/myReviews" | "/dashboard/user/profile" | "/dashboard/user/userDeliveryHistory" | "/dashboard/user/userOverview" | "/pricing/payment-success" | "/signin" | "/signup" | "/unauthorized"
type AppRouteHandlerRoutes = "/api/ai/chat" | "/api/auth/session" | "/api/payment"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard" | "/dashboard/admin" | "/dashboard/librarian" | "/dashboard/user"
type RedirectRoutes = never
type RewriteRoutes = "/api/ai/[[...path]]" | "/api/send-email"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/ai/[[...path]]": { "path"?: string[]; }
  "/api/ai/chat": {}
  "/api/auth/session": {}
  "/api/payment": {}
  "/api/send-email": {}
  "/books": {}
  "/books/[id]": { "id": string; }
  "/dashboard": {}
  "/dashboard/admin": {}
  "/dashboard/admin/bookApproval": {}
  "/dashboard/admin/manageBooks": {}
  "/dashboard/admin/overview": {}
  "/dashboard/admin/profile": {}
  "/dashboard/admin/users": {}
  "/dashboard/admin/viewTransactions": {}
  "/dashboard/librarian": {}
  "/dashboard/librarian/addBook": {}
  "/dashboard/librarian/manageDeliveries": {}
  "/dashboard/librarian/manageInventory": {}
  "/dashboard/librarian/overview": {}
  "/dashboard/librarian/profile": {}
  "/dashboard/user": {}
  "/dashboard/user/myReadingList": {}
  "/dashboard/user/myReviews": {}
  "/dashboard/user/profile": {}
  "/dashboard/user/userDeliveryHistory": {}
  "/dashboard/user/userOverview": {}
  "/pricing/payment-success": {}
  "/signin": {}
  "/signup": {}
  "/unauthorized": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
  "/dashboard/admin": never
  "/dashboard/librarian": never
  "/dashboard/user": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
