// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(auth)/signin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signin">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/signin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/admin/bookApproval/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/bookApproval">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/admin/bookApproval/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/admin/manageBooks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/manageBooks">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/admin/manageBooks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/admin/overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/overview">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/admin/overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/admin/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/profile">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/admin/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/admin/viewTransactions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/viewTransactions">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/admin/viewTransactions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/librarian/addBook/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/librarian/addBook">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/librarian/addBook/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/librarian/manageDeliveries/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/librarian/manageDeliveries">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/librarian/manageDeliveries/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/librarian/manageInventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/librarian/manageInventory">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/librarian/manageInventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/librarian/overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/librarian/overview">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/librarian/overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/librarian/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/librarian">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/librarian/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/librarian/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/librarian/profile">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/librarian/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/user/myReadingList/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/user/myReadingList">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/user/myReadingList/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/user/myReviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/user/myReviews">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/user/myReviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/user/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/user">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/user/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/user/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/user/profile">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/user/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/user/userDeliveryHistory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/user/userDeliveryHistory">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/user/userDeliveryHistory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/user/userOverview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/user/userOverview">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/user/userOverview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/books/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/books/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/books/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/books/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/books">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/books/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pricing/payment-success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing/payment-success">> = Specific
  const handler = {} as typeof import("../../src/app/pricing/payment-success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/unauthorized/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/unauthorized">> = Specific
  const handler = {} as typeof import("../../src/app/unauthorized/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/chat">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/session">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payment">> = Specific
  const handler = {} as typeof import("../../src/app/api/payment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/admin">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/librarian/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/librarian">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/librarian/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/user/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/user">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/user/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
