var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/(main)/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1k1zyoy._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_12u8poj.js")
R.c("server/chunks/ssr/[root-of-the-server]__1pn2a5r._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1zcd-31._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_@opentelemetry_api_index_1oy1nwh.js")
R.c("server/chunks/ssr/_084k08x._.js")
R.c("server/chunks/ssr/src_0expj-y._.js")
R.c("server/chunks/ssr/_1m4j_s6._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0p8s4lh._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/src_0fewvyr._.js")
R.c("server/chunks/ssr/src_app_(main)_loading_tsx_0ni4ktt._.js")
R.c("server/chunks/ssr/_1_o3v2j._.js")
R.c("server/chunks/ssr/_0fh5sxu._.js")
R.m(51801)
module.exports=R.m(51801).exports
