var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ln09ua._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0m_i6ao.js")
R.c("server/chunks/ssr/[root-of-the-server]__1pn2a5r._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1zcd-31._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_@opentelemetry_api_index_1oy1nwh.js")
R.c("server/chunks/ssr/_084k08x._.js")
R.c("server/chunks/ssr/src_0expj-y._.js")
R.c("server/chunks/ssr/_1m4j_s6._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0p8s4lh._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/_next-internal_server_app__not-found_page_actions_0pt47yr.js")
R.m(60465)
module.exports=R.m(60465).exports
