var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/unauthorized/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__015jhl9._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0dy-jlg.js")
R.c("server/chunks/ssr/[root-of-the-server]__1pn2a5r._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1zcd-31._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_@opentelemetry_api_index_1oy1nwh.js")
R.c("server/chunks/ssr/_084k08x._.js")
R.c("server/chunks/ssr/src_0expj-y._.js")
R.c("server/chunks/ssr/_1m4j_s6._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0p8s4lh._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_unauthorized_page_actions_1588edm.js")
R.m(30961)
module.exports=R.m(30961).exports
