var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(auth)/signin/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1ih3ccg._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_1cxohib.js")
R.c("server/chunks/ssr/[root-of-the-server]__1pn2a5r._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1zcd-31._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_@opentelemetry_api_index_1oy1nwh.js")
R.c("server/chunks/ssr/_084k08x._.js")
R.c("server/chunks/ssr/src_0expj-y._.js")
R.c("server/chunks/ssr/_1m4j_s6._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0p8s4lh._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/src_app_(auth)_layout_tsx_1gtd5vn._.js")
R.c("server/chunks/ssr/src_app_(auth)_loading_tsx_0vnorxt._.js")
R.c("server/chunks/ssr/src_app_(auth)_signin_loading_tsx_1g43bz_._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(auth)_signin_page_actions_0srl2je.js")
R.m(6060)
module.exports=R.m(6060).exports
